export interface PatternModifier {
  id: string;
  name: string;
  template: string;
  exampleSeed: string;
  typicalSv: string;
  kdRange: string;
  archetype: 'tool' | 'programmatic_db' | 'apk_hub' | 'transactional' | 'authority_blog';
  aiOverviewImmunity: 'High (100% Immune)' | 'Medium' | 'Low';
  description: string;
  suggestedCountries: string[];
}

export interface PatternBucket {
  id: string;
  title: string;
  badge: string;
  iconName: string;
  color: string;
  description: string;
  idealArchetype: string;
  monetization: string;
  rpmRange: string;
  modifiers: PatternModifier[];
}

export const MASTER_PATTERN_VAULT: PatternBucket[] = [
  {
    id: 'ai-outputs',
    title: '1. AI + Specific Output Generators',
    badge: 'High Anomaly / Fast Build',
    iconName: 'Sparkles',
    color: 'purple',
    description: 'Specific outputs that users want generated (e.g. AI floor plan, AI tattoo, AI signature). Beats generic "AI tool" intent with DR < 20 anomalies capturing 50k+ organic traffic.',
    idealArchetype: 'Single-Page Interactive Tool / Next.js Canvas / Micro-SaaS',
    monetization: 'Freemium Pro Credits, Tier 1 Display Ads ($35-$52 RPM), Affiliate AI Tools',
    rpmRange: '$35 – $55 / 1k visits',
    modifiers: [
      {
        id: 'ai-floor-plan',
        name: 'AI Floor Plan / Layout',
        template: 'ai floor plan',
        exampleSeed: 'ai floor plan',
        typicalSv: '45,000 - 90,000',
        kdRange: '15 - 28',
        archetype: 'tool',
        aiOverviewImmunity: 'High (100% Immune)',
        description: 'Target anomaly: DR 17 site getting 57k+ monthly traffic with simple 2D/3D layout generator canvas.',
        suggestedCountries: ['United States', 'Canada', 'United Kingdom', 'Australia'],
      },
      {
        id: 'ai-tattoo',
        name: 'AI Tattoo Generator',
        template: 'ai tattoo generator',
        exampleSeed: 'ai tattoo generator',
        typicalSv: '60,000 - 150,000',
        kdRange: '18 - 32',
        archetype: 'tool',
        aiOverviewImmunity: 'High (100% Immune)',
        description: 'High commercial & hobby search volume. DR 12 sites ranking #1 with visual canvas and prompt library.',
        suggestedCountries: ['United States', 'United Kingdom', 'Canada', 'Germany'],
      },
      {
        id: 'ai-signature',
        name: 'AI Signature Generator',
        template: 'ai signature generator',
        exampleSeed: 'ai signature generator',
        typicalSv: '30,000 - 80,000',
        kdRange: '12 - 24',
        archetype: 'tool',
        aiOverviewImmunity: 'High (100% Immune)',
        description: 'Zero AI Overview risk because users need an interactive downloadable PNG/SVG signature.',
        suggestedCountries: ['United States', 'India', 'United Kingdom', 'Canada'],
      },
      {
        id: 'ai-hairstyle',
        name: 'AI Hairstyle / Haircut Try-On',
        template: 'ai hairstyle generator',
        exampleSeed: 'ai hairstyle generator',
        typicalSv: '80,000 - 220,000',
        kdRange: '20 - 35',
        archetype: 'tool',
        aiOverviewImmunity: 'High (100% Immune)',
        description: 'Massive viral traffic. Low DR wrappers capturing millions in global traffic with photo upload tool.',
        suggestedCountries: ['United States', 'United Kingdom', 'India', 'Germany', 'France'],
      },
      {
        id: 'ai-room-design',
        name: 'AI Room / Interior Design',
        template: 'ai room design',
        exampleSeed: 'ai interior design',
        typicalSv: '40,000 - 110,000',
        kdRange: '16 - 30',
        archetype: 'tool',
        aiOverviewImmunity: 'High (100% Immune)',
        description: 'High RPM home decor and architectural affiliate monetization ($40+ RPM).',
        suggestedCountries: ['United States', 'Canada', 'United Kingdom', 'Australia', 'Germany'],
      },
      {
        id: 'ai-headshot',
        name: 'AI Headshot / Avatar Generator',
        template: 'ai headshot generator',
        exampleSeed: 'ai headshot generator',
        typicalSv: '50,000 - 140,000',
        kdRange: '22 - 38',
        archetype: 'tool',
        aiOverviewImmunity: 'High (100% Immune)',
        description: 'Direct high-ticket B2B monetization ($29-$49 per headshot pack) + high affiliate payouts.',
        suggestedCountries: ['United States', 'United Kingdom', 'Canada', 'Australia'],
      },
      {
        id: 'ai-logo',
        name: 'AI Logo & Icon Generator',
        template: 'ai logo generator',
        exampleSeed: 'ai logo generator free',
        typicalSv: '90,000 - 280,000',
        kdRange: '25 - 42',
        archetype: 'tool',
        aiOverviewImmunity: 'High (100% Immune)',
        description: 'Evergreen transactional intent with instant vector/SVG downloads.',
        suggestedCountries: ['United States', 'India', 'United Kingdom', 'Germany'],
      },
    ],
  },
  {
    id: 'programmatic-specs',
    title: '2. Programmatic Specs, Tables & Data',
    badge: '100% AI Overview Immune',
    iconName: 'Layers',
    color: 'emerald',
    description: 'Tabular databases, dimensions, error codes, prices, and APN settings. Google AI Overview cannot summarize deep structured matrices, creating bulletproof organic traffic.',
    idealArchetype: 'Programmatic Database (500+ URLs with searchable filters & comparison tables)',
    monetization: 'High-RPM Display Ads ($30-$52 RPM) + Relevant Product Affiliate CTAs',
    rpmRange: '$30 – $52 / 1k visits',
    modifiers: [
      {
        id: 'brand-prices',
        name: 'Brand Prices & Speisekarte',
        template: '[brand] prices',
        exampleSeed: 'starbucks prices',
        typicalSv: '25,000 - 180,000',
        kdRange: '10 - 25',
        archetype: 'programmatic_db',
        aiOverviewImmunity: 'High (100% Immune)',
        description: 'Local and national menu pricing tables. In Germany/France/US, DR 2-8 sites rank #1.',
        suggestedCountries: ['United States', 'Germany', 'United Kingdom', 'Canada', 'France'],
      },
      {
        id: 'obd2-error-codes',
        name: 'Diagnostic & Error Codes',
        template: '[device/car] error code [X]',
        exampleSeed: 'samsung washer error code 4c',
        typicalSv: '35,000 - 120,000',
        kdRange: '8 - 22',
        archetype: 'programmatic_db',
        aiOverviewImmunity: 'High (100% Immune)',
        description: 'OBD2 car codes, appliance blinking lights, boiler faults. 1,000+ programmatic pages generated from standard code charts.',
        suggestedCountries: ['United States', 'United Kingdom', 'Canada', 'Australia'],
      },
      {
        id: 'tire-dimensions',
        name: 'Tire Sizes & Rim Bolt Dimensions',
        template: '[car make model] tire size',
        exampleSeed: 'toyota rav4 tire size',
        typicalSv: '40,000 - 150,000',
        kdRange: '12 - 26',
        archetype: 'programmatic_db',
        aiOverviewImmunity: 'High (100% Immune)',
        description: 'Huge automotive replacement tire search volume. High affiliate commission on TireRack/Amazon.',
        suggestedCountries: ['United States', 'Canada', 'United Kingdom', 'Germany'],
      },
      {
        id: 'apn-settings',
        name: 'APN & Router Settings',
        template: '[carrier] apn settings',
        exampleSeed: 't-mobile apn settings',
        typicalSv: '30,000 - 110,000',
        kdRange: '5 - 18',
        archetype: 'programmatic_db',
        aiOverviewImmunity: 'High (100% Immune)',
        description: 'Zero KD technical configurations for global telecom carriers.',
        suggestedCountries: ['United States', 'India', 'Pakistan', 'United Kingdom', 'South Africa'],
      },
      {
        id: 'restaurant-calories',
        name: 'Restaurant Calories, Macros & Allergens',
        template: '[restaurant] calories macros',
        exampleSeed: 'chipotle nutrition calories',
        typicalSv: '50,000 - 200,000',
        kdRange: '14 - 28',
        archetype: 'programmatic_db',
        aiOverviewImmunity: 'High (100% Immune)',
        description: 'Fitness enthusiasts and dieters searching for exact item calorie & carb tables.',
        suggestedCountries: ['United States', 'United Kingdom', 'Canada', 'Australia'],
      },
      {
        id: 'salary-calculators',
        name: 'Salary, Tax & Dosage Calculators',
        template: '[state/country] salary tax calculator',
        exampleSeed: 'california salary paycheck calculator',
        typicalSv: '60,000 - 250,000',
        kdRange: '15 - 32',
        archetype: 'tool',
        aiOverviewImmunity: 'High (100% Immune)',
        description: 'Interactive JS widgets with zero AI overview threat. Ultra-high financial RPM ($50-$85 RPM).',
        suggestedCountries: ['United States', 'United Kingdom', 'Canada', 'Germany', 'Australia'],
      },
    ],
  },
  {
    id: 'high-volume-apks',
    title: '3. High-Volume Regional APKs & Gaming Utilities',
    badge: 'KD 0 with 100K+ Volume',
    iconName: 'Zap',
    color: 'amber',
    description: 'Massive mobile gaming and app download search volume in Tier 2/3 markets (India, Pakistan, Brazil, SE Asia) with KD 0-10 where DR 0-5 sites capture 100,000+ monthly visits.',
    idealArchetype: 'APK Download Gateway / App Version Hub with Changelogs & Safety Hashes',
    monetization: 'Direct App Installs (CPI $0.50-$2.00), Push Ads, PropellerAds, AdSense',
    rpmRange: '$4 – $14 / 1k visits',
    modifiers: [
      {
        id: 'rummy-gaming-apk',
        name: 'Card & Gaming APKs',
        template: '[game] apk',
        exampleSeed: 'yono rummy apk',
        typicalSv: '80,000 - 250,000',
        kdRange: '0 - 10',
        archetype: 'apk_hub',
        aiOverviewImmunity: 'High (100% Immune)',
        description: 'Real screenshot case: "yono rummy apk" has KD 0 with 121,000 monthly search volume!',
        suggestedCountries: ['India', 'Pakistan', 'Bangladesh'],
      },
      {
        id: 'streaming-mod-apk',
        name: 'Streaming & Video Mod APKs',
        template: '[app] apk download',
        exampleSeed: 'pikashow apk',
        typicalSv: '150,000 - 450,000',
        kdRange: '15 - 45',
        archetype: 'apk_hub',
        aiOverviewImmunity: 'High (100% Immune)',
        description: 'Mega-demand search volumes (200k+ searches) in South Asia & LATAM.',
        suggestedCountries: ['India', 'Pakistan', 'Indonesia', 'Brazil'],
      },
      {
        id: 'pc-emulator-apk',
        name: 'Android Apps for PC / Old Versions',
        template: '[app] for pc download',
        exampleSeed: 'capcut for pc windows 10',
        typicalSv: '40,000 - 180,000',
        kdRange: '10 - 25',
        archetype: 'apk_hub',
        aiOverviewImmunity: 'High (100% Immune)',
        description: 'High intent guide and direct download links for desktop users.',
        suggestedCountries: ['United States', 'India', 'United Kingdom', 'Brazil'],
      },
    ],
  },
  {
    id: 'commercial-buy',
    title: '4. High-Commercial Intent "Buy" Transactions',
    badge: 'Direct Revenue Goldmine',
    iconName: 'DollarSign',
    color: 'blue',
    description: 'Transactional queries where users have payment cards ready to purchase digital assets, coins, credits, subscribers, or virtual numbers.',
    idealArchetype: 'Transactional Reseller / Service Provider Landing Page with Stripe / Crypto Checkout',
    monetization: 'Direct Service Sales (50-80% margins), Affiliate Reseller Commissions (20-40%)',
    rpmRange: '$60 – $150 / 1k visits (High Conversion)',
    modifiers: [
      {
        id: 'buy-social-subscribers',
        name: 'Buy Subscribers / Views / Followers',
        template: 'buy [platform] subscribers',
        exampleSeed: 'buy youtube subscribers pakistan',
        typicalSv: '15,000 - 75,000',
        kdRange: '10 - 28',
        archetype: 'transactional',
        aiOverviewImmunity: 'High (100% Immune)',
        description: 'Extremely lucrative transaction volume in localized markets with automated SMM panel APIs.',
        suggestedCountries: ['Pakistan', 'India', 'United States', 'United Kingdom', 'United Arab Emirates'],
      },
      {
        id: 'buy-game-coins',
        name: 'Buy Gaming Coins & Top-Ups',
        template: 'buy [game] coins',
        exampleSeed: 'buy roblox robux cheap',
        typicalSv: '30,000 - 120,000',
        kdRange: '14 - 30',
        archetype: 'transactional',
        aiOverviewImmunity: 'High (100% Immune)',
        description: 'High frequency digital repeat purchases with automated gift card API fulfillment.',
        suggestedCountries: ['United States', 'United Kingdom', 'Germany', 'Saudi Arabia'],
      },
      {
        id: 'buy-virtual-numbers',
        name: 'Buy Virtual Numbers & SMS Verification',
        template: 'buy virtual number for [service]',
        exampleSeed: 'buy virtual number for whatsapp',
        typicalSv: '25,000 - 90,000',
        kdRange: '8 - 22',
        archetype: 'transactional',
        aiOverviewImmunity: 'High (100% Immune)',
        description: 'Recurring micro-transactions with high profit margins via 5sim/SMS-Activate APIs.',
        suggestedCountries: ['India', 'Pakistan', 'United States', 'United Kingdom', 'Germany'],
      },
    ],
  },
  {
    id: 'geo-arbitrage',
    title: '5. Geo & Multi-Language Arbitrage',
    badge: 'Tier 1 RPM ($40-$52) / 0 Competition',
    iconName: 'Globe',
    color: 'rose',
    description: 'Translating high-demand English patterns into German, French, Spanish, and Dutch. Ranking takes weeks instead of months because authority competition is virtually non-existent.',
    idealArchetype: 'Localized Programmatic Hub or Niche Authority Blog in Native Language',
    monetization: 'Mediavine / AdThrive / Google AdSense (German/Swiss/French RPMs average $38-$55)',
    rpmRange: '$38 – $55 / 1k visits',
    modifiers: [
      {
        id: 'german-preise',
        name: 'German Preise & Speisekarten',
        template: '[brand] preise / speisekarte',
        exampleSeed: 'mcdonalds preise deutschland',
        typicalSv: '35,000 - 160,000',
        kdRange: '5 - 18',
        archetype: 'programmatic_db',
        aiOverviewImmunity: 'High (100% Immune)',
        description: 'Huge German search volume with $45+ RPM and DR 5 sites ranking on position #1.',
        suggestedCountries: ['Germany', 'Austria', 'Switzerland'],
      },
      {
        id: 'french-tarifs',
        name: 'French Tarifs & Menus',
        template: '[brand] tarif prix',
        exampleSeed: 'burger king prix menu france',
        typicalSv: '25,000 - 120,000',
        kdRange: '4 - 16',
        archetype: 'programmatic_db',
        aiOverviewImmunity: 'High (100% Immune)',
        description: 'Zero competition from major media publishers, effortless ranking for fresh exact-match domains.',
        suggestedCountries: ['France', 'Belgium', 'Canada'],
      },
      {
        id: 'spanish-precios',
        name: 'Spanish Precios & Codigos de Error',
        template: '[brand] precios / [device] codigos error',
        exampleSeed: 'starbucks precios espana',
        typicalSv: '30,000 - 140,000',
        kdRange: '6 - 20',
        archetype: 'programmatic_db',
        aiOverviewImmunity: 'High (100% Immune)',
        description: 'Large cross-border traffic spanning Spain, Mexico, Argentina, and Colombia.',
        suggestedCountries: ['Spain', 'Mexico', 'Argentina'],
      },
    ],
  },
  {
    id: 'challenger-brands',
    title: '6. Challenger Brands & Secondary Chains',
    badge: 'DR 0-5 Ranking Anomaly',
    iconName: 'Target',
    color: 'indigo',
    description: 'Targeting secondary challenger brands (Popeyes, Arby\'s, Little Caesars, Five Guys, Tim Hortons, Jollibee) rather than apex saturated giants (McDonald\'s), enabling fast $500+/mo ranking anomalies.',
    idealArchetype: 'Brand-Dedicated Micro Site (Exact Menu, Secret Items, Nutrition, Store Hours)',
    monetization: 'High RPM Display Ads ($32-$48 RPM) + Delivery App Affiliate Commissions',
    rpmRange: '$32 – $48 / 1k visits',
    modifiers: [
      {
        id: 'popeyes-menu',
        name: 'Popeyes Menu & Secret Items',
        template: 'popeyes menu prices with pictures',
        exampleSeed: 'popeyes menu with prices',
        typicalSv: '90,000 - 240,000',
        kdRange: '18 - 29',
        archetype: 'programmatic_db',
        aiOverviewImmunity: 'High (100% Immune)',
        description: 'Massive organic food intent with low DR niche sites capturing $2,000+/mo in ad revenue.',
        suggestedCountries: ['United States', 'Canada', 'United Kingdom'],
      },
      {
        id: 'little-caesars',
        name: 'Little Caesars Pizza Prices & Deals',
        template: 'little caesars menu prices',
        exampleSeed: 'little caesars menu and prices',
        typicalSv: '70,000 - 180,000',
        kdRange: '15 - 26',
        archetype: 'programmatic_db',
        aiOverviewImmunity: 'High (100% Immune)',
        description: 'High weekly recurring demand for pizza deals and local outlet pricing.',
        suggestedCountries: ['United States', 'Canada', 'Mexico'],
      },
      {
        id: 'tim-hortons',
        name: 'Tim Hortons Menu & Nutrition Guide',
        template: 'tim hortons menu prices canada',
        exampleSeed: 'tim hortons menu prices',
        typicalSv: '80,000 - 210,000',
        kdRange: '16 - 28',
        archetype: 'programmatic_db',
        aiOverviewImmunity: 'High (100% Immune)',
        description: 'Dominant national search demand in Canada with ultra-high local Tier 1 RPMs.',
        suggestedCountries: ['Canada', 'United States', 'United Kingdom'],
      },
    ],
  },
];
